{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "todo.fullname" . }}-db
  labels:
    {{- include "todo.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.externalSecrets.secretStoreName }}
  target:
    name: {{ .Values.rds.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.rds.ssmPrefix }}/host
    - secretKey: DB_PORT
      remoteRef:
        key: {{ .Values.rds.ssmPrefix }}/port
    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.rds.ssmPrefix }}/database
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.rds.ssmPrefix }}/username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.rds.ssmPrefix }}/master-password
{{- end }}
