apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo.fullname" . }}-frontend
  labels:
    {{- include "todo.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "todo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "todo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      volumes:
        - name: nginx-tmp
          emptyDir: {}
      containers:
        - name: frontend
          image: {{ include "todo.image" (dict "registry" .Values.imageRegistry "repository" .Values.frontend.image.repository "tag" .Values.frontend.image.tag) }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 101
            runAsGroup: 101
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: nginx-tmp
              mountPath: /tmp
