apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo.fullname" . }}-frontend
  labels:
    {{- include "todo.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
  selector:
    {{- include "todo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
